[settings]
gpg_verify = false

[tools]
"aqua:astral-sh/uv" = "latest"
"aqua:dandavison/delta" = "latest"
"aqua:hashicorp/vault" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
go = "latest"
jq = "latest"
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@charmland/crush" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:npmrc" = "latest"
"npm:vibe-rules" = "latest"
"pipx:basedpyright" = "latest"
python = "latest"
ruby = "3.3.6"
rust = "latest"
usage = "latest"

[env]
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{ get_env(name='XDG_CONFIG_HOME', default='~/.config') }}/mise/default-npm-packages"
